CREATE TABLE `t_bidcollect_one_level_page` (
  `id` int NOT NULL AUTO_INCREMENT,
  `webname` varchar(255) DEFAULT NULL COMMENT '网站名称',
  `webadd` varchar(255) DEFAULT NULL COMMENT '网址',
  `href` varchar(255) DEFAULT NULL COMMENT '分页链接',
  `flag` varchar(3) DEFAULT NULL COMMENT '爬取方式',
  `lastdate` timestamp NULL DEFAULT NULL COMMENT '最后爬取日期',
  `isfail` varchar(20) DEFAULT NULL COMMENT '爬取失败',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `method` varchar(3) DEFAULT NULL COMMENT '爬虫方法',
  `find_list` varchar(255) DEFAULT NULL COMMENT '公告列表位置',
  `find_href` varchar(500) DEFAULT NULL COMMENT '详情页链接位置',
  `find_title` varchar(255) DEFAULT NULL COMMENT '公告名称位置',
  `find_pub_time` varchar(255) DEFAULT NULL COMMENT '发布日期位置',
  `find_zbid` varchar(255) DEFAULT NULL COMMENT '招标公告id',
  `post_content_href` varchar(255) DEFAULT NULL COMMENT 'post详情页链接',
  `find_content` varchar(255) DEFAULT NULL COMMENT '公告内容位置',
  `post_payload1` mediumtext COMMENT '爬列表页负载',
  `post_payload2` mediumtext COMMENT '爬详情页负载',
  `post_headers` mediumtext COMMENT 'post请求头',
  `u` varchar(255) DEFAULT '无',
  `p` varchar(255) DEFAULT '无',
  `last_collect_time` datetime DEFAULT NULL COMMENT '最后采集时间',
  `list_method` enum('get_html','post_html','get_json','post_json','selenium') NOT NULL DEFAULT 'get_html',
  `detail_method` enum('get_html','post_html','get_json','post_json','selenium') NOT NULL DEFAULT 'get_html',
  `page_params` varchar(255) DEFAULT NULL,
  `frequency` int DEFAULT NULL COMMENT '更新频率',
  `is_active` tinyint(1) DEFAULT '1',
  `quchong_weburl` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_t_bidcollect_one_level_page_href` (`href`)
) ENGINE=InnoDB AUTO_INCREMENT=11522 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='规则配置表'


CREATE TABLE `t_bidcollect_end_level_page` (
  `id` int NOT NULL AUTO_INCREMENT,
  `webname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '网站名称',
  `href` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '分页链接',
  `p_href` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '父链接',
  `flag` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '爬取方式',
  `publish_time` date DEFAULT NULL,
  `isexec` tinyint(1) DEFAULT NULL COMMENT '是否爬过',
  `isfail` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '爬取失败',
  `industry` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '行业类型',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '爬虫方法',
  `find_content` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '爬公告内容',
  `zbid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '招标公告id',
  `post_content_href` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'post详情页链接',
  `post_payload1` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '爬详情页负载',
  `post_headers` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '请求头',
  `u` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `p` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `detail_method` enum('get_html','post_html','get_json','post_json','selenium') NOT NULL DEFAULT 'get_html',
  `one_level_page_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_01` (`href`),
  KEY `idx_t_bidcollect_end_level_page_p_href_create_time` (`p_href`,`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=779430092 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='公告列表'


CREATE TABLE `t_bidcollect_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `webname` varchar(255) DEFAULT NULL,
  `href` varchar(512) NOT NULL,
  `msg` mediumtext,
  `html` longtext COMMENT 'html',
  `publish_time` date NOT NULL,
  `industry` varchar(255) DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tohtml` varchar(1) DEFAULT '0',
  `u` varchar(100) DEFAULT NULL,
  `p` varchar(100) DEFAULT NULL,
  `method` varchar(2) DEFAULT NULL COMMENT ' 01:request,02:playwrite',
  `from_auto_script` int DEFAULT NULL,
  `areaProvince` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `identify_code` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`,`publish_time`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `webname_href` (`webname`,`href`),
  KEY `idx_pubtime` (`publish_time`) USING BTREE,
  KEY `idx_createtime` (`create_time`) USING BTREE,
  KEY `idx_fromauto` (`from_auto_script`) USING BTREE,
  KEY `idx_href` (`href`),
  KEY `idx_idfy_code` (`identify_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=150204156 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
